Repository kaltura/playkit-js-ima-dai, pull requests merged in 2019-05, with the labels that each got.

#6 fix(FEC-9048): click event is not dispatched
  src/ima-dai.js
Labels: Type: Bug

#7 fix(FEC-9075): resume ad from toolbar doesn't work
  src/ima-dai.js
Labels: Priority: High, Type: Bug

#9 fix(FEC-9081): wrong state when seeking into ad in pause mode
  src/ima-dai.js
Labels: Priority: High, Type: Bug

#8 fix(FEC-9080): when seeking back from end screen no play button displayed
  src/ima-dai-event-manager.js
Labels: Priority: High, Type: Bug

#10 fix(FEC-9086): the screen blinking and endless spinner displayed when replay is ended
  src/ima-dai.js
Labels: Priority: High, Type: Bug

#11 fix: ad system is missing in the ad event payload
  src/ima-dai.js
Labels: Priority: High, Type: Bug

#12 fix(FEC-9088): play button displayed instead of pause, when playback started anew in loop (loopback)
  src/ima-dai.js
Labels: Priority: High, Type: Bug

#13 fix(FEC-9089): can seek over mid-roll using iPhone native player
  src/ima-dai.js
Labels: Priority: High, Type: Bug

#14 chore(FEC-9066): README.MD
  README.md
  docs/api.md
  flow-typed/types/ima-dai-config.js
  src/ima-dai-ads-controller.js
  src/ima-dai.js
Labels: Priority: High, Type: Docs
